export const SKELETON_STORE = 'SKELETON_STORE';
export const SKELETON_TYPE_INIT = 'SKELETON_TYPE_INIT';
export const SKELETON_TYPE_CHANGE = 'SKELETON_TYPE_CHANGE';
export const SKELETON_STATUS_LOADING = 'SKELETON_STATUS_LOADING';
export const SKELETON_STATUS_INIT = 'SKELETON_STATUS_INIT';
