export const SKELETON_STORE = 'SKELETON_STORE';
export const SKELETON_TYPE_INIT = 'SKELETON_TYPE_INIT';
export const SKELETON_TYPE_CHANGE = 'SKELETON_TYPE_CHANGE';
export const SKELETON_STATUS_LOADING = 'SKELETON_STATUS_LOADING';
export const SKELETON_STATUS_INIT = 'SKELETON_STATUS_INIT';
export const SKELETON_GET_NAME = 'SKELETON_GET_NAME';
export const SKELETON_GET_TITLE = 'SKELETON_GET_TITLE';
export const SKELETON_GET_DONE = 'SKELETON_GET_DONE';
